@extends('layouts.app')
@section('title', 'Project Templates')
@section('content')
    <div class="w-full px-4 py-4 md:px-8">
        <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 class="text-3xl font-bold text-slate-900">Project Templates</h1><p class="mt-1 text-sm text-slate-500">Kelola pola project, hierarchy, dependency, weight, dan jadwal relatif.</p></div>@can('project-templates.create')<a href="{{ route('project-templates.create') }}" class="inline-flex items-center justify-center gap-2 rounded-xl bg-sky-600 px-4 py-2.5 text-sm font-semibold text-white"><i class="fa-solid fa-plus"></i>Buat Template</a>@endcan</div>
        @if(session('success'))<div class="mb-5 rounded-xl border border-green-200 bg-green-50 p-4 text-sm text-green-700">{{ session('success') }}</div>@endif
        <div class="mb-5 flex flex-wrap gap-2 border-b border-slate-200"><a href="{{ route('project-templates.index') }}" class="border-b-2 border-sky-600 px-4 py-3 text-sm font-semibold text-sky-700">Templates</a>@can('project-template-categories.view')<a href="{{ route('project-template-categories.index') }}" class="px-4 py-3 text-sm font-semibold text-slate-500 hover:text-sky-700">Categories</a>@endcan</div>
        <form method="GET" class="mb-5 grid gap-3 lg:grid-cols-[1fr_240px_180px_auto]"><input type="search" name="search" value="{{ $search }}" placeholder="Cari template..." class="rounded-xl border-slate-300"><select name="category_id" class="rounded-xl border-slate-300"><option value="">Semua kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($categoryId === $category->id)>{{ $category->name }}</option>@endforeach</select><select name="status" class="rounded-xl border-slate-300"><option value="">Semua status</option><option value="active" @selected($status === 'active')>Aktif</option><option value="inactive" @selected($status === 'inactive')>Tidak aktif</option></select><button class="rounded-xl bg-slate-700 px-5 py-2.5 text-sm font-semibold text-white">Filter</button></form>
        <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[960px] text-left text-sm"><thead class="bg-sky-100 text-xs uppercase text-slate-600"><tr><th class="px-5 py-4">Template</th><th class="px-5 py-4">Kategori</th><th class="px-5 py-4">Version</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Task</th><th class="px-5 py-4">Total Beban</th><th class="px-5 py-4">Creator / Update</th><th class="px-5 py-4 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">
            @forelse($templates as $template)<tr class="hover:bg-slate-50"><td class="px-5 py-4"><a href="{{ route('project-templates.show', $template) }}" class="font-semibold text-sky-700 hover:underline">{{ $template->name }}</a><p class="text-xs text-slate-400">{{ $template->slug }}</p></td><td class="px-5 py-4">{{ $template->category->name }}</td><td class="px-5 py-4">{{ $template->version }}</td><td class="px-5 py-4">@include('project-templates.partials._status-badge')</td><td class="px-5 py-4">{{ $template->tasks_count }}</td><td class="px-5 py-4 font-semibold">{{ number_format($template->totalLeafWeight($template->tasks), 2) }}</td><td class="px-5 py-4">{{ $template->updater?->name ?? $template->creator?->name ?? '—' }}</td><td class="px-5 py-4"><div class="flex justify-end gap-2"><a href="{{ route('project-templates.show', $template) }}" class="rounded-lg p-2 text-sky-600 hover:bg-sky-50"><i class="fa-solid fa-eye"></i></a>@can('project-templates.update')<a href="{{ route('project-templates.edit', $template) }}" class="rounded-lg p-2 text-amber-600 hover:bg-amber-50"><i class="fa-solid fa-pen"></i></a>@endcan</div></td></tr>
            @empty<tr><td colspan="8" class="px-5 py-12 text-center text-slate-400">Belum ada project template.</td></tr>@endforelse
        </tbody></table></div>@if($templates->hasPages())<div class="border-t border-slate-200 p-4">{{ $templates->links() }}</div>@endif</div>
    </div>
@endsection
